'use strict';
//timeConsuming
export const START_HANDLE_TIME_CONSUMING = 'START_HANDLE_TIME_CONSUMING';
export const STOP_HANDLE_TIME_CONSUMING = 'STOP_HANDLE_TIME_CONSUMING';
//login
export const FETCH_LOGIN_RESULT = 'FETCH_LOGIN_RESULT';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';
export const CHANGE_LOGIN_AUTH = 'CHANGE_LOGIN_AUTH';
//tabIndex
export const FETCH_NEWS_RESULT = 'FETCH_NEWS_RESULT';
export const RECEIVE_NEWS_RESULT = 'RECEIVE_NEWS_RESULT';
export const FETCH_TASK_COUNT_RESULT = 'FETCH_TASK_COUNT_RESULT';
export const RECEIVE_TASK_COUNT_RESULT = 'RECEIVE_TASK_COUNT_RESULT';
//tabOffice
export const FETCH_OFFICE_ITEM_RESULT = 'FETCH_OFFICE_ITEM_RESULT';
export const RECEIVE_OFFICE_ITEM_RESULT = 'RECEIVE_OFFICE_ITEM_RESULT';
//webview
// export const FETCH_NOTICE_RESULT = 'FETCH_NOTICE_RESULT';
// export const RECEIVE_NOTICE_RESULT = 'RECEIVE_NOTICE_RESULT';
export const CHANGE_WEBVIEW_URL = 'CHANGE_WEBVIEW_URL';
//noticeList
export const FETCH_NOTICE_LIST_RESULT = 'FETCH_NOTICE_LIST_RESULT';
export const RECEIVE_NOTICE_LIST_RESULT = 'RECEIVE_NOTICE_LIST_RESULT';
//address
export const FETCH_ADDRESS_SEARCH_RESULT = 'FETCH_ADDRESS_SEARCH_RESULT';
export const RECEIVE_ADDRESS_SEARCH_RESULT = 'RECEIVE_ADDRESS_SEARCH_RESULT';
export const CHANGE_ADDRESS_SEARCH_NAME = 'CHANGE_ADDRESS_SEARCH_NAME';
export const ASSIGN_ADDRESS_LIST_DATA = 'ASSIGN_ADDRESS_LIST_DATA';
//userInfo
export const FETCH_AVATAR_RESULT = 'FETCH_AVATAR_RESULT';
export const RECEIVE_AVATAR_RESULT = 'RECEIVE_AVATAR_RESULT';
export const FETCH_INFO_RESULT = 'FETCH_INFO_RESULT';
export const RECEIVE_INFO_RESULT = 'RECEIVE_INFO_RESULT';
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';
export const UPLOAD_AVATAR_RESULT = 'UPLOAD_AVATAR_RESULT';
export const RECEIVE_UPLOAD_AVATAR_RESULT = 'RECEIVE_UPLOAD_AVATAR_RESULT';
export const FETCH_COMMIT_USER_INFO_RESULT = 'FETCH_COMMIT_USER_INFO_RESULT';
export const RECEIVE_COMMIT_USER_INFO_RESULT = 'RECEIVE_COMMIT_USER_INFO_RESULT';
//changePassword
export const FETCH_CHANGE_PASSWORD_RESULT = 'FETCH_CHANGE_PASSWORD_RESULT';
export const RECEIVE_CHANGE_PASSWORD_RESULT = 'RECEIVE_CHANGE_PASSWORD_RESULT';
export const CHANGE_NEW_PASSWORD = 'CHANGE_NEW_PASSWORD';
//officeTemplateList
export const FETCH_OFFICE_TEMPLATE_RESULT = 'FETCH_OFFICE_TEMPLATE_RESULT';
export const RECEIVE_OFFICE_TEMPLATE_RESULT = 'RECEIVE_OFFICE_TEMPLATE_RESULT';
//officeForm
export const FETCH_OFFICE_FORM_RESULT = 'FETCH_OFFICE_FORM_RESULT';
export const RECEIVE_OFFICE_FORM_RESULT = 'RECEIVE_OFFICE_FORM_RESULT';
export const CHANGE_OFFICE_FORM_KEYBOARD_SPACE = 'CHANGE_OFFICE_FORM_KEYBOARD_SPACE';
export const HANDLE_FORM_USER_INPUT = 'HANDLE_FORM_USER_INPUT';
export const HANDLE_TABLE_USER_INPUT = 'HANDLE_TABLE_USER_INPUT';
export const ASSIGN_TABLE_DATA = 'ASSIGN_TABLE_DATA';
export const ASSIGN_TABLE_INPUT_DATA = 'ASSIGN_TABLE_INPUT_DATA';
export const FETCH_COMMIT_OFFICE_FORM_RESULT = 'FETCH_COMMIT_OFFICE_FORM_RESULT';
export const RECEIVE_COMMIT_OFFICE_FORM_RESULT = 'RECEIVE_COMMIT_OFFICE_FORM_RESULT';
export const RECEIVE_COMMIT_OFFICE_FORM_EDIT = 'RECEIVE_COMMIT_OFFICE_FORM_EDIT';
export const RECEIVE_COMMIT_OFFICE_FORM_CLEAREDIT = 'RECEIVE_COMMIT_OFFICE_FORM_CLEAREDIT';
//taskList
export const FETCH_TASK_LIST_RESULT = 'FETCH_TASK_LIST_RESULT';
export const RECEIVE_TASK_LIST_RESULT = 'RECEIVE_TASK_LIST_RESULT';
//taskDetail
export const FETCH_TASK_DETAIL_RESULT = 'FETCH_TASK_DETAIL_RESULT';
export const RECEIVE_TASK_DETAIL_RESULT = 'RECEIVE_TASK_DETAIL_RESULT';
//taskApproval
export const FETCH_TASK_APPROVAL_FROM_RESULT = 'FETCH_TASK_APPROVAL_FROM_RESULT';
export const RECEIVE_TASK_APPROVAL_FORM_RESULT = 'RECEIVE_TASK_APPROVAL_FORM_RESULT';
export const CHANGE_APPROVAL_FORM_KEYBOARD_SPACE = 'CHANGE_APPROVAL_FORM_KEYBOARD_SPACE';
export const HANDLE_APPROVAL_USER_INPUT = 'HANDLE_APPROVAL_USER_INPUT';
export const FETCH_COMMIT_APPROVAL_RESULT = 'FETCH_COMMIT_APPROVAL_RESULT';
export const RECEIVE_COMMIT_APPROVAL_RESULT = 'RECEIVE_COMMIT_APPROVAL_RESULT';
export const FETCH_APPROVAL_BUTTON_RESULT = 'FETCH_APPROVAL_BUTTON_RESULT';
export const RECEIVE_APPROVAL_BUTTON_RESULT = 'RECEIVE_APPROVAL_BUTTON_RESULT';
export const FETCH_OTHER_APPROVAL_RESULT = 'FETCH_OTHER_APPROVAL_RESULT';
export const RECEIVE_OTHER_APPROVAL_RESULT = 'RECEIVE_OTHER_APPROVAL_RESULT';
//firstLogined
export const FETCH_FIRSTLOGIN_RESULT = 'FETCH_FIRSTLOGIN_RESULT';
export const RECETIVE_FIRSTLOGIN_RESULT = 'RECETIVE_FIRSTLOGIN_RESULT';
export const FIRSTLOGIN = 'FIRSTLOGIN';
export const CHANGE_FIRSTLOGIN_KEYBOARD_SPACE = 'CHANGE_FIRSTLOGIN_KEYBOARD_SPACE';
//staff
export const FETCH_STAFF_LIST_RESULT = 'FETCH_STAFF_LIST_RESULT';
export const RECEIVE_STAFF_LIST_RESULT = 'RECEIVE_STAFF_LIST_RESULT';
export const CHANGE_STAFF_SEARCH_NAME = 'CHANGE_STAFF_SEARCH_NAME';
export const CHANGE_STAFF_REMARK = 'CHANGE_STAFF_REMARK';
export const ASSIGN_STAFF_LIST_DATA = 'ASSIGN_STAFF_LIST_DATA';
export const ASSIGN_STAFF_USER_ID = 'ASSIGN_STAFF_USER_ID';
//messageList
export const FETCH_MESSAGE_LIST_RESULT = 'FETCH_MESSAGE_LIST_RESULT';
export const RECEIVE_MESSAGE_LIST_RESULT = 'RECEIVE_MESSAGE_LIST_RESULT';
//contactList
export const FETCH_CONTACT_LIST_RESULT = 'FETCH_CONTACT_LIST_RESULT';
export const RECEIVE_CONTACT_LIST_RESULT = 'RECEIVE_CONTACT_LIST_RESULT';
export const FETCH_CONTACT_BUSINESS_TYPE_RESULT = 'FETCH_CONTACT_BUSINESS_TYPE_RESULT';
export const RECEIVE_CONTACT_BUSINESS_TYPE_RESULT = 'RECEIVE_CONTACT_BUSINESS_TYPE_RESULT';
export const FETCH_CONTACT_DETAIL_RESULT = 'FETCH_CONTACT_DETAIL_RESULT';
export const RECEIVE_CONTACT_DETAIL_RESULT = 'RECEIVE_CONTACT_DETAIL_RESULT';
export const HANDLE_CONTACT_USER_INPUT = 'HANDLE_CONTACT_USER_INPUT';
export const FETCH_CONTACT_CREATE_RESULT = 'FETCH_CONTACT_CREATE_RESULT';
export const RECEIVE_CONTACT_CREATE_RESULT = 'RECEIVE_CONTACT_CREATE_RESULT';
export const FETCH_CONTACT_FOLLOW_TYPE_RESULT = 'FETCH_CONTACT_FOLLOW_TYPE_RESULT';
export const RECEIVE_CONTACT_FOLLOW_TYPE_RESULT = 'RECEIVE_CONTACT_FOLLOW_TYPE_RESULT';
export const FETCH_CONTACT_APPROVE_RESULT = 'FETCH_CONTACT_APPROVE_RESULT';
export const RECEIVE_CONTACT_APPROVE_RESULT = 'RECEIVE_CONTACT_APPROVE_RESULT';
